/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 't.hun' at '12/03/18 16:24' with Gradle 3.0
 *
 * @author t.hun, @date 12/03/18 16:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
